// 9 frozen pages: the top-level feature pages, as Contentful held them the day
// they were taken out of it. This file IS the source — there is no CMS read
// behind it any more, so a copy change is an edit here and a deploy.
//
// Generated by scripts/freeze-cms.mts. Regenerating overwrites hand edits, so
// once you start editing the copy here, stop regenerating: the CMS entries are
// no longer maintained. Imagery lives in public/images/cms, downloaded with it.
import type { CmsPage } from "./cms-page";
import {
  SIGNUP_URL,
  DEMO_URL,
  GUIDE_URL,
  TRUST_CENTER_URL,
} from "./constants";

export const FROZEN_FEATURES: CmsPage[] = [
  {
    "slug": "client-management",
    "seo": {
      "title": "Best AI-Powered CRM for Professional Services",
      "description": "Centralize data, automate workflows, and build stronger client relationships with AI-powered CRM software. Try Assembly free."
    },
    "noIndex": false,
    "hero": {
      "title": "Client management for the modern service business",
      "description": "CRM software built for professional service firms to organize and centralize their client management.",
      "ctas": [
        {
          "label": "Get started",
          "href": SIGNUP_URL
        },
        {
          "label": "Book a demo",
          "href": DEMO_URL
        }
      ],
      "image": {
        "url": "/images/cms/3VPZYPWGkgxSMhBH2VTW9t-we_1.webp",
        "alt": "Hero Image / CRM",
        "width": 1422,
        "height": 2132
      },
      "layout": "left"
    },
    "sections": [
      {
        "kind": "features",
        "title": "Create a truly custom CRM for your business",
        "description": "Whether you work with individuals or companies, build detailed client records that serve as a single source of truth, customized for your business.",
        "ctas": [],
        "image": {
          "url": "/images/cms/2bIDBAn3QvH6wuJPdySuZV-crm_value_prop_1.webp",
          "alt": "Client Portal 1 Custom CRM Tinified",
          "width": 2400,
          "height": 1096
        }
      },
      {
        "kind": "features",
        "title": "Manage clients in one place",
        "description": "Keep client work simple with integrated messaging, billing, and task management—all connected in one platform.",
        "ctas": [],
        "features": [
          {
            "label": "Invoicing",
            "heading": "Invoice clients in one place",
            "body": "Keep client work simple with integrated billing — all connected in one platform.",
            "image": {
              "url": "/images/cms/2ftHXucWwAyr7KIj7Za1i-invoicing_billing.webp",
              "alt": "Invoicing Billing",
              "width": 2400,
              "height": 1096
            }
          },
          {
            "label": "Contracts",
            "heading": "Request eSignatures in one place",
            "body": "Keep client work simple with integrated contracts and forms.",
            "image": {
              "url": "/images/cms/1WGMaXT9b1Q9sglhiO41b2-contracts.webp",
              "alt": "Contracts 1",
              "width": 2400,
              "height": 1096
            }
          },
          {
            "label": "Tasks",
            "heading": "Assign clients tasks and project manage together.",
            "body": "Keep your team and clients on track with integrated project management tools.",
            "image": {
              "url": "/images/cms/2t0yce48LH4iJPQmBiyAGC-tasks.webp",
              "alt": "Tasks",
              "width": 2400,
              "height": 1096
            }
          }
        ]
      },
      {
        "kind": "features",
        "title": "Get organized with an AI-powered back office",
        "description": "Keep your team aligned with internal chat, AI assistance, and firm-wide visibility controls.",
        "ctas": [],
        "image": {
          "url": "/images/cms/2cdYJOc2NsvOb9OLuXMrnI-ai_backoffice.webp",
          "alt": "AI office",
          "width": 2400,
          "height": 1096
        }
      },
      {
        "kind": "grid",
        "title": "A secure client portal that ties it all together",
        "description": "Deliver a bespoke client experience with powerful tools and enterprise-grade compliance, at no extra cost.",
        "ctas": [
          {
            "label": "Explore client portal",
            "href": "https://assembly.com/client-portal"
          }
        ],
        "items": [
          {
            "title": "Custom team permissions",
            "description": "Assign team members access to only certain clients.",
            "href": "https://assembly.com/guide/client-access"
          },
          {
            "title": "Security",
            "description": "Enterprise-grade protection built in from day one.",
            "href": TRUST_CENTER_URL
          }
        ]
      }
    ],
    "closing": {
      "title": "Your clients deserve better.",
      "description": "Try Assembly for free, no credit card required.",
      "ctas": [
        {
          "label": "Get started",
          "href": SIGNUP_URL
        },
        {
          "label": "Book a demo",
          "href": DEMO_URL
        }
      ]
    }
  },
  {
    "slug": "client-onboarding-system",
    "seo": {
      "title": "Best Client Onboarding System for Professionals",
      "description": "Offer clients a smooth start by collecting forms, sending contracts, and managing payments securely within Assembly's Customer Onboarding Software."
    },
    "noIndex": false,
    "hero": {
      "title": "Make client onboarding effortless",
      "description": "Focus on building relationships. Assembly lets you automate messages, contracts, file-sharing and more in one portal.",
      "ctas": [
        {
          "label": "Get started",
          "href": SIGNUP_URL
        },
        {
          "label": "Book a demo",
          "href": DEMO_URL
        }
      ],
      "image": {
        "url": "/images/cms/5GAwPD14bKlVaddAKBxZTC-onboarding_hero_rectangle.webp",
        "alt": "Portal",
        "width": 2400,
        "height": 1425
      },
      "layout": "center"
    },
    "sections": [
      {
        "kind": "features",
        "title": "Make the first impression count",
        "description": "With Assembly, you get a branded client portal that houses all your contracts, forms, and welcome materials for a professional polish.",
        "ctas": [],
        "features": [
          {
            "label": "Messaging",
            "heading": "Manage clients in one place",
            "body": "Keep client work simple with integrated messaging, billing, and task management—all connected in one platform.",
            "image": {
              "url": "/images/cms/2xcB10EJxj4GNjrM6j0T0L-messaging.webp",
              "alt": "Messaging",
              "width": 2400,
              "height": 1096
            }
          },
          {
            "label": "CRM",
            "heading": "Create a truly custom CRM for your business",
            "body": "Whether you work with individuals or companies, build detailed client records that serve as a single source of truth, customized for your business.",
            "image": {
              "url": "/images/cms/2bIDBAn3QvH6wuJPdySuZV-crm_value_prop_1.webp",
              "alt": "Client Portal 1 Custom CRM Tinified",
              "width": 2400,
              "height": 1096
            }
          }
        ]
      },
      {
        "kind": "features",
        "title": "Focus on your clients, not admin",
        "description": "Automate repeatable steps like sending contracts, collecting payments, and sharing files—so you spend less time chasing details and more time delivering value.",
        "ctas": [],
        "image": {
          "url": "/images/cms/3WNAV9RNkJElvugXehl0iw-automations.webp",
          "alt": "Platform VP 3 Automations",
          "width": 2400,
          "height": 1096
        }
      },
      {
        "kind": "features",
        "title": "Give clients everything in one place",
        "description": "Forget juggling emails, spreadsheets, and file links. Your clients get one secure hub for forms, tasks, messages, and documents. It’s simple for them, and streamlined for you.",
        "ctas": [],
        "image": {
          "url": "/images/cms/23VVaRTGtFKSdMvP1aVPP5-everything_in_one_place.webp",
          "alt": "Box Files",
          "width": 2400,
          "height": 1096
        }
      },
      {
        "kind": "grid",
        "title": "Choose what works best for your client onboarding",
        "description": "Deliver a custom, streamlined client onboarding with powerful tools and features in your portal, at no extra cost.",
        "ctas": [
          {
            "label": "Explore client portal",
            "href": "https://assembly.com/client-portal"
          },
          {
            "label": "Book a demo",
            "href": DEMO_URL
          }
        ],
        "items": [
          {
            "title": "Forms & Integration",
            "description": "Collect client info up front and sync with your existing tools.",
            "href": "https://assembly.com/apps/directory/forms-app"
          },
          {
            "title": "Billing & Invoicing",
            "description": "Send one-off payment requests, recurring subscription invoices, and make it easy to pay with credit cards and ACH.",
            "href": "https://assembly.com/invoicing"
          },
          {
            "title": "Contracts & eSignatures",
            "description": "Clients sign legally binding contracts in your portal.",
            "href": "https://assembly.com/esignature",
            "icon": {
              "url": "/images/cms/3scRmzUrKzXFLuoWq64SuI-icon_-_pencil-outline.svg",
              "alt": "Icon - Rich text editor"
            }
          },
          {
            "title": "Secure file sharing",
            "description": "Share and request documents securely in your portal.",
            "href": "https://assembly.com/file-sharing",
            "icon": {
              "url": "/images/cms/3ipz2j90k5hh1po2etisZV-file-sharing_app-icon.svg",
              "alt": "File-sharing"
            }
          },
          {
            "title": "Custom applications",
            "description": "Connect with the team to discuss creating custom applications.",
            "href": DEMO_URL,
            "icon": {
              "url": "/images/cms/57aoJSfqcz3GYQ9vY63jVi-icon_-_home-outline.svg",
              "alt": "image"
            }
          }
        ]
      }
    ],
    "closing": {
      "title": "Your clients deserve better.",
      "description": "Try Assembly for free, no credit card required.",
      "ctas": [
        {
          "label": "Get started",
          "href": SIGNUP_URL
        },
        {
          "label": "Book a demo",
          "href": DEMO_URL
        }
      ]
    }
  },
  {
    "slug": "client-communication-tool",
    "seo": {
      "title": "Customer Communication Management (CCM) Software",
      "description": "Improve client relationships with an all-in-one communication platform with built-in messaging, scheduling and booking integrations, and more."
    },
    "noIndex": false,
    "hero": {
      "title": "Improve your client communication",
      "description": "Ditch scattered emails and phone calls. Assembly’s client portal is a secure customer communication platform with built-in messaging and more.",
      "ctas": [
        {
          "label": "Get started",
          "href": SIGNUP_URL
        },
        {
          "label": "Book a demo",
          "href": DEMO_URL
        }
      ],
      "image": {
        "url": "/images/cms/38RsUKFBYBsugS4qqEaliV-hero_-_comms_rectangle.webp",
        "alt": "Hero - Client Comms",
        "width": 2400,
        "height": 1525
      },
      "layout": "center"
    },
    "sections": [
      {
        "kind": "features",
        "title": "One platform for every client interaction",
        "description": "Your clients' messages, tasks, and files live in the portal. But clients don’t have to change their habits: they can reply by email and their messages sync automatically.",
        "ctas": [],
        "features": [
          {
            "label": "Messaging",
            "heading": "Manage clients in one place",
            "body": "Keep client work simple with integrated messaging, billing, and task management—all connected in one platform.",
            "image": {
              "url": "/images/cms/2xcB10EJxj4GNjrM6j0T0L-messaging.webp",
              "alt": "Messaging",
              "width": 2400,
              "height": 1096
            }
          },
          {
            "label": "Tasks",
            "heading": "Assign clients tasks and project manage together.",
            "body": "Keep your team and clients on track with integrated project management tools.",
            "image": {
              "url": "/images/cms/2t0yce48LH4iJPQmBiyAGC-tasks.webp",
              "alt": "Tasks",
              "width": 2400,
              "height": 1096
            }
          },
          {
            "label": "File sharing",
            "heading": "Share files securely",
            "body": "Share files with your clients in a secure data platform with custom permissions.",
            "image": {
              "url": "/images/cms/1ZI5PJ1p7NSShB52WZACA8-file_sharing.webp",
              "alt": "File Sharing",
              "width": 2400,
              "height": 1526
            }
          }
        ]
      },
      {
        "kind": "features",
        "title": "Clear communication, less busy work",
        "description": "Automate responses, create helpdesk guides for common questions, and send automatic email reminders.",
        "ctas": [],
        "image": {
          "url": "/images/cms/29CAgi0RChicJIG0MKT4sS-communication_prop_2.webp",
          "alt": "Communication Prop 2",
          "width": 2400,
          "height": 1096
        }
      },
      {
        "kind": "features",
        "title": "Secure channels for multiple clients and teams",
        "description": "Create flexible message channels for multiple clients in multiple companies. Configure messaging with custom permissions and visibility.",
        "ctas": [],
        "image": {
          "url": "/images/cms/18JPjDsBxA3Ozwl11EB8pW-communications_prop_3.webp",
          "alt": "Communications Prop 3",
          "width": 2400,
          "height": 1096
        }
      },
      {
        "kind": "grid",
        "title": "More ways to power your client experience",
        "description": "Deliver a bespoke client experience with powerful tools and features in your portal, at no extra cost.",
        "ctas": [
          {
            "label": "Explore client portal",
            "href": "https://assembly.com/client-portal"
          },
          {
            "label": "Book a demo",
            "href": DEMO_URL
          }
        ],
        "items": [
          {
            "title": "Security & Compliance",
            "description": "Features for SOC 2, HIPAA compliant portals built-in.",
            "href": TRUST_CENTER_URL
          },
          {
            "title": "Billing & Invoicing",
            "description": "Send one-off payment requests, recurring subscription invoices, and make it easy to pay with credit cards and ACH.",
            "href": "https://assembly.com/invoicing"
          },
          {
            "title": "Scheduling via Calendly",
            "description": "Let clients book meetings with our Calendly integration.",
            "href": "https://assembly.com/apps/directory/calendly",
            "icon": {
              "url": "/images/cms/6jY4WshRdW2PLTFcqK7NOc-icon_-_grayscale_-_calendly-1.svg",
              "alt": "Icon - Grayscale - calendly-1"
            }
          },
          {
            "title": "Contracts & eSignatures",
            "description": "Clients sign legally binding contracts in your portal.",
            "href": "https://assembly.com/esignature",
            "icon": {
              "url": "/images/cms/3scRmzUrKzXFLuoWq64SuI-icon_-_pencil-outline.svg",
              "alt": "Icon - Rich text editor"
            }
          },
          {
            "title": "Client onboarding",
            "description": "Save time with automatic onboarding using custom forms and messages.",
            "href": "https://assembly.com/client-onboarding-system",
            "icon": {
              "url": "/images/cms/4O7BmINOo7n0haKVFyRQfb-icon_-_create_clients_one_at_a_time.svg",
              "alt": "Icon - Create clients one at a time"
            }
          }
        ]
      }
    ],
    "closing": {
      "title": "Your clients deserve better.",
      "description": "Try Assembly for free, no credit card required.",
      "ctas": [
        {
          "label": "Get started",
          "href": SIGNUP_URL
        },
        {
          "label": "Book a demo",
          "href": DEMO_URL
        }
      ]
    }
  },
  {
    "slug": "invoicing",
    "seo": {
      "title": "Best Invoicing Software for Small Businesses",
      "description": "Assembly offers an easy-to-use invoicing platform for small businesses, startups, agencies, and modern firms that value security and reliability."
    },
    "noIndex": false,
    "hero": {
      "title": "Get paid faster with modern invoicing software",
      "description": "Try the best invoice software for modern service-based businesses. Generate polished invoices in seconds so you can spend more time on what matters for your business.",
      "ctas": [
        {
          "label": "Get started",
          "href": SIGNUP_URL
        }
      ],
      "image": {
        "url": "/images/cms/20nVaT9Yd7xumLrElHUHYG-invoice_header.webp",
        "alt": "Invoicing header",
        "width": 1916,
        "height": 2532
      },
      "layout": "left"
    },
    "sections": [
      {
        "kind": "features",
        "title": "Streamlined invoice management for your team",
        "description": "Simplify your invoice system: save time with customizable invoices, tailored payment options and ways to track unpaid invoices with ease.",
        "ctas": [],
        "features": [
          {
            "label": "Invoice generator",
            "heading": "Invoice generator",
            "body": "Create unlimited online invoices with customizable invoice templates, tailored payment options, and surcharge options.",
            "image": {
              "url": "/images/cms/3jTjogKqED9xQuirsamWMJ-invoice_tab_1.webp",
              "alt": "invoice-creation",
              "width": 2400,
              "height": 1490
            }
          },
          {
            "label": "Invoice management",
            "heading": "Invoice management",
            "body": "Manage unpaid invoices, spot overdue payments, send reminders, view billing analytics, and export data.",
            "image": {
              "url": "/images/cms/4hkcoUxSV4euQE9MIsIE6g-invoice-management.webp",
              "alt": "invoice-management",
              "width": 2400,
              "height": 1490
            }
          },
          {
            "label": "Products & Subscriptions",
            "heading": "Products & Subscriptions",
            "body": "Set up products and recurring subscriptions once and save time by using them whenever needed. Streamline your workflow and focus on what matters most.",
            "image": {
              "url": "/images/cms/B1DJfSbe1XoNsRQcujr3w-products-and-prices.webp",
              "alt": "products-and-prices",
              "width": 2400,
              "height": 1490
            }
          }
        ]
      },
      {
        "kind": "grid",
        "title": "A professional tool for professional firms",
        "description": "Secure data with enterprise-grade safeguards (SOC2, HIPAA) and automate invoices with built-in tools, external APIs and webhooks. Track revenue in real-time analytics, automate billing workflows, and personalize the experience with branding and a custom domain.",
        "ctas": [],
        "items": [
          {
            "title": "Security",
            "description": "Keep data safe with enterprise-grade SOC 2 and HIPAA compliance.",
            "href": TRUST_CENTER_URL,
            "icon": {
              "url": "/images/cms/2z1KZwfUyLReXXIbaJNS0f-icon_-_security.svg",
              "alt": "Icon - Security"
            }
          },
          {
            "title": "API",
            "description": "Use API endpoints and webhooks to take actions when invoices are paid.",
            "icon": {
              "url": "/images/cms/2dg9VHqTOEx0EozpAUbvYX-image.webp",
              "alt": "image"
            }
          },
          {
            "title": "Analytics",
            "description": "Gain real-time billing insights, track revenue trends, and make data-driven decisions.",
            "icon": {
              "url": "/images/cms/htnAENdWN5Lym20Hmev3F-image.webp",
              "alt": "Analytics"
            }
          },
          {
            "title": "Automations",
            "description": "Set up workflows that save you time with client management.",
            "href": "https://assembly.com/platform",
            "icon": {
              "url": "/images/cms/1flRTHSmPccu6P8zLbquBy-33.svg",
              "alt": "automation"
            }
          },
          {
            "title": "Branding",
            "description": "Create personalized online invoices and let clients checkout on a custom domain.",
            "href": "https://assembly.com/client-portal",
            "icon": {
              "url": "/images/cms/jkTvwtvwnppGpPpmpmeQR-image.webp",
              "alt": "Branding"
            }
          },
          {
            "title": "Portal",
            "description": "Give clients a unified platform to pay invoices, message you, sign contracts, and more.",
            "icon": {
              "url": "/images/cms/6sVk8FCxPdpCi3XjNfgnm4-image.webp",
              "alt": "portal"
            }
          },
          {
            "title": "Reminders",
            "description": "Automate payment reminders to keep clients on track and minimize overdue invoices.",
            "icon": {
              "url": "/images/cms/3liUPOBucIXJB42uht0Zgx-image.webp",
              "alt": "Reminder"
            }
          },
          {
            "title": "Surcharging",
            "description": "Add and configure surcharges to minimize payment processing fees.",
            "icon": {
              "url": "/images/cms/5oHzhC0ZjH2YUwC0t6gwmj-image.webp",
              "alt": "Surcharging"
            }
          }
        ]
      },
      {
        "kind": "features",
        "title": "A world-class checkout & invoicing experience",
        "description": "Make a polished checkout experience with a fully branded customer portal where clients can pay while staying immersed in your brand. Flexible payment options streamline the experience for your customers.",
        "ctas": [],
        "features": [
          {
            "label": "Payments",
            "heading": "Online invoice payments and checkout",
            "body": "Clients can pay using credit cards, debit cards, ACH bank transfer, or Apple Pay—all through a mobile-friendly, branded portal. Whether on their phone or desktop, your clients enjoy a seamless payment experience designed for their convenience.",
            "image": {
              "url": "/images/cms/1bx1Ags23AZ2YHiIDBXbL7-checkout.webp",
              "alt": "modern checkout",
              "width": 2400,
              "height": 1513
            }
          },
          {
            "label": "Invoice tracking",
            "heading": "Self-serve invoice histories",
            "body": "Clients can easily manage their own accounts with self-serve access to invoice histories, downloadable invoices, and payment method updates—all available anytime through your branded portal. Simplify their experience while saving your team time.",
            "image": {
              "url": "/images/cms/28FZgU1U5L7G3vySqZa2xQ-self-serve-access-2.webp",
              "alt": "self-serve-acces",
              "width": 2400,
              "height": 1513
            }
          },
          {
            "label": "Customer portal",
            "heading": "Integrated customer portal",
            "body": "Assembly goes beyond payments to support you in every aspect of client collaboration. Send messages and share files with clients, create forms for quotes, automate your contract workflow, and create self-serve help articles all in one place.",
            "image": {
              "url": "/images/cms/619Q83uBzrB4Tg1LWuVOuD-integrated-portal-2.webp",
              "alt": "integrated-portal",
              "width": 2400,
              "height": 1513
            }
          }
        ]
      },
      {
        "kind": "grid",
        "title": "More than just invoicing",
        "description": "Take your professional services beyond basic invoicing with an integrated, branded client portal.",
        "ctas": [],
        "items": [
          {
            "title": "Client portal",
            "description": "Give clients access to messages, contracts, files, and more.",
            "href": "https://assembly.com/client-portal",
            "icon": {
              "url": "/images/cms/1PkNte2UVDmgRgv39rXEj0-client-portal_app-icon.svg",
              "alt": "Client portal"
            }
          },
          {
            "title": "Automations",
            "description": "Set up workflows that save you time with client management.",
            "href": "https://assembly.com/platform",
            "icon": {
              "url": "/images/cms/1flRTHSmPccu6P8zLbquBy-33.svg",
              "alt": "automation"
            }
          },
          {
            "title": "Subscriptions",
            "description": "Automate recurring payments and billing cycles for predictable revenue",
            "href": "https://assembly.com/guide/assembly-billing-app#subscriptions",
            "icon": {
              "url": "/images/cms/OduVerJi5FZcgOs7a2DAJ-subscription_app-icon.svg",
              "alt": "Subscriptions"
            }
          },
          {
            "title": "File-sharing",
            "description": "Share files and documents securely with easy client access and permissions.",
            "href": "https://assembly.com/file-sharing",
            "icon": {
              "url": "/images/cms/3ipz2j90k5hh1po2etisZV-file-sharing_app-icon.svg",
              "alt": "File-sharing"
            }
          },
          {
            "title": "Tasks",
            "description": "Manage tasks seamlessly across your team and clients in one place.",
            "href": "https://assembly.com/apps/directory/tasks",
            "icon": {
              "url": "/images/cms/63n3excnJirrH269FFqVYg-tasks_app-icon.svg",
              "alt": "Tasks"
            }
          },
          {
            "title": "Security",
            "description": "Keep data safe with enterprise-grade SOC 2 and HIPAA compliance.",
            "href": TRUST_CENTER_URL,
            "icon": {
              "url": "/images/cms/2z1KZwfUyLReXXIbaJNS0f-icon_-_security.svg",
              "alt": "Icon - Security"
            }
          },
          {
            "title": "CRM",
            "description": "Manage client relationships and track every interaction in one hub.",
            "href": "https://assembly.com/client-management",
            "icon": {
              "url": "/images/cms/un13D37gCMBXuvKbPG1k6-crm_app-icon.svg",
              "alt": "CRM"
            }
          },
          {
            "title": "Forms",
            "description": "Create custom intake forms to collect client information efficiently.",
            "href": "https://assembly.com/apps/directory/forms-app",
            "icon": {
              "url": "/images/cms/7bo7hIwcb0sUrJXbvbJ95O-forms_app-icon.svg",
              "alt": "Forms"
            }
          },
          {
            "title": "Contracts",
            "description": "Send professional agreements with built-in eSignatures.",
            "href": "https://assembly.com/esignature",
            "icon": {
              "url": "/images/cms/5J51JMXqLiyazZsh8RvvoH-contracts_app-icon.svg",
              "alt": "Contracts"
            }
          }
        ]
      },
      {
        "kind": "faq",
        "title": "Frequently asked questions",
        "items": [
          {
            "question": "How is Assembly different from Stripe, Zoho, Bill.com, Wave, and others?",
            "answer": "Assembly’s invoicing features aren’t just standalone — our platform integrates contracts, forms, file-sharing, messaging, and more in one seamless hub. This allows you to create automated workflows that streamline onboarding and payment collection in a white-labeled portal. \n\nYour clients can sign a contract, complete a form, and pay an invoice all within the same branded experience.\n\nOn the backend, having everything consolidated on a single platform means unified notifications and permissions for your team. Instead of juggling multiple logins and tools, you manage all client interactions, payment processes, and documents in one place. \n\nThis unified view simplifies collaboration, reduces confusion, and keeps everyone aligned."
          },
          {
            "question": "How are payment processing fees structured?",
            "answer": "Our payment processing costs are transparent and in line with industry standards. There’s a base fee for credit cards and ACH payments, plus an additional fee depending on the type of billing entity — whether you’re sending a one-off invoice or setting up a subscription. \n\nDetailed rates, including specifics for both credit card and ACH transactions, are clearly outlined on our pricing page for your reference."
          },
          {
            "question": "Which payment methods are supported?",
            "answer": "Your clients can pay using credit cards, debit cards, ACH, and Apple Pay. We’re always exploring new payment methods to offer even more flexibility."
          },
          {
            "question": "Can I pass fees onto my clients?",
            "answer": "Absolutely. \n\nSurcharging is natively supported, and you have granular control over which fees get passed along. For example, you might choose to pass on credit card fees to client but absorb the ACH fees yourself, tailoring the fee structure to fit your business model."
          },
          {
            "question": "Do you support recurring invoices and subscriptions?",
            "answer": "Yes.\n\nBeyond one-time invoices, Assembly's Payments App is built for recurring payments and subscription management. You can set up auto-renewals, pause or resume subscriptions, and handle billing changes effortlessly, all through a single, centralized platform."
          },
          {
            "question": "How do I invoice someone for a payment?",
            "answer": "1. Create an invoice template.\n2. Upload your invoice template to Assembly’s Billing > Invoices section.\n3. Add your client’s details, list the services or products provided, set due dates, and more,\n4. Connect your preferred payment method. \n5. Assembly can send your client a link to payment once complete.\n\nWith Assembly, clients can view and pay invoices directly through a secure, branded portal—streamlining your billing process and getting you paid faster."
          },
          {
            "question": "What is an invoicing system?",
            "answer": "An invoicing system can be software that helps businesses create, send, and manage invoices for products or services. It streamlines the billing process, tracks payments, and improves cash flow. \n\nAssembly invoicing is built directly into a secure, customizable client portal, allowing you to send professional invoices, accept payments online, and give clients a seamless billing experience. \n\nAssembly's invoicing system helps service businesses get paid faster while maintaining a polished, branded client experience."
          }
        ]
      }
    ],
    "closing": {
      "title": "Modern invoicing for modern businesses",
      "description": "Try for free, no credit card required",
      "ctas": [
        {
          "label": "Get started",
          "href": SIGNUP_URL
        },
        {
          "label": "Book a demo",
          "href": DEMO_URL
        }
      ]
    }
  },
  {
    "slug": "file-sharing",
    "seo": {
      "title": "Secure Client File Sharing Portal",
      "description": "Secure, branded file sharing made simple. SOC 2 and HIPAA-compliant portal software for professional firms. Try Assembly free."
    },
    "noIndex": false,
    "hero": {
      "title": "Secure file sharing that looks and feels like your brand",
      "description": "Send documents to customers with a secure portal that carries your brand—not someone else’s.",
      "ctas": [
        {
          "label": "Get started",
          "href": SIGNUP_URL
        },
        {
          "label": "Book a demo",
          "href": DEMO_URL
        }
      ],
      "image": {
        "url": "/images/cms/2EfR9jB5Lx9lmXmApe8np6-hero_file_share.webp",
        "alt": "File Sharing Hero",
        "width": 1224,
        "height": 706
      },
      "layout": "center"
    },
    "sections": [
      {
        "kind": "features",
        "title": "Secure for your industry, simple for your clients",
        "description": "No more unsecured email attachments. Whether it’s tax documents, medical records, or legal files, Assembly protects your data with SOC 2 and HIPAA-compliant file-sharing in a portal your clients will love.",
        "ctas": [],
        "image": {
          "url": "/images/cms/32c3kDCj10Fpbtym3hUbr-file_share_vp_1.webp",
          "alt": "File Share VP 1",
          "width": 1758,
          "height": 1118
        }
      },
      {
        "kind": "features",
        "title": "Automate your file sharing",
        "description": "Less tedious manual work. When clients sign up, you can automatically create files and folders for them based on their needs.",
        "ctas": [],
        "features": [
          {
            "label": "Automate",
            "heading": "Focus on your clients, not admin",
            "body": "Automate repeatable steps like sending contracts, collecting payments, and sharing files—so you spend less time chasing details and more time delivering value.",
            "image": {
              "url": "/images/cms/3WNAV9RNkJElvugXehl0iw-automations.webp",
              "alt": "Platform VP 3 Automations",
              "width": 2400,
              "height": 1096
            }
          }
        ]
      },
      {
        "kind": "features",
        "title": "A single source of truth for client work",
        "description": "Keep contracts, invoices, conversations, and files in one place. With Assembly, your firm and your clients always know where to look.",
        "ctas": [],
        "features": [
          {
            "label": "Client Portal",
            "heading": "Make the first impression count",
            "body": "With Assembly, you get a branded client portal that houses all your contracts, forms, and welcome materials for a professional polish.",
            "image": {
              "url": "/images/cms/7JFnBgIrmwJETs1w4TxWMz-client_home_complete.webp",
              "alt": "Client Home Portal",
              "width": 2400,
              "height": 1096
            }
          }
        ]
      },
      {
        "kind": "grid",
        "title": "Integrate seamlessly with your existing storage",
        "description": "Connect or embed external storage solutions into your branded client portal.",
        "ctas": [
          {
            "label": "View app store",
            "href": "https://assembly.com/apps/directory"
          }
        ],
        "items": [
          {
            "title": "Google Drive",
            "description": "Embed drive folders for easy access for clients.",
            "href": "https://assembly.com/apps/directory/google-drive"
          },
          {
            "title": "Microsoft OneDrive",
            "description": "Connect a file or folder from OneDrive and let clients view it directly in your portal.",
            "href": "https://assembly.com/apps/directory/onedrive"
          }
        ]
      }
    ],
    "closing": {
      "title": "Your clients deserve better.",
      "description": "Try Assembly for free, no credit card required.",
      "ctas": [
        {
          "label": "Get started",
          "href": SIGNUP_URL
        },
        {
          "label": "Book a demo",
          "href": DEMO_URL
        }
      ]
    }
  },
  {
    "slug": "client-portal",
    "seo": {
      "title": "Assembly Client Portal | Best White Label Customer Portals",
      "description": "Build custom, white-labeled client portals with secure messaging, file sharing, and billing - no-code required. Try Assembly free."
    },
    "noIndex": false,
    "hero": {
      "title": "Make secure, white-labeled customer portals",
      "description": "Impress clients with a modern customer experience that streamlines onboarding, communication, and payments in your own branded client portal.",
      "ctas": [
        {
          "label": "Get started",
          "href": SIGNUP_URL
        }
      ],
      "image": {
        "url": "/images/cms/5r4qnmmK9XOFu8Sd23HUTh-eeeee_2.webp",
        "alt": "Hero Client Portal",
        "width": 1068,
        "height": 1230
      },
      "layout": "left"
    },
    "sections": [
      {
        "kind": "features",
        "title": "Give your clients a unified experience",
        "description": "Assembly’s white-labeled client portal delivers a one-stop shop customer experience, with instant chat messaging, file sharing, eSignature contracts, invoicing, and more — managed in one place.",
        "ctas": [],
        "features": [
          {
            "label": "Onboarding",
            "heading": "Streamline your client onboarding",
            "body": "Quickly set up an onboarding experience that walks clients through a clear task checklist —from submitting forms, signing contracts, to paying the first invoice — so nothing falls through the cracks.",
            "href": "/customers/collective-cpa",
            "image": {
              "url": "/images/cms/6NCh8DcLxvSIPn38TxAuai-final_image_herpo_1.webp",
              "alt": "Feature 1 / Client Onboarding Portal",
              "width": 1968,
              "height": 1066
            }
          },
          {
            "label": "Collaborate",
            "heading": "Start collaborative projects",
            "body": "As projects begin, keep everyone on track by assigning tasks to your team and your clients. Add comments and mentions so that you can resolve issues and move forward smoothly.",
            "image": {
              "url": "/images/cms/5DAWwtx1HIilBdQjG1YrKe-tasks.webp",
              "alt": "Feature 2 / Collaborative Projects",
              "width": 2400,
              "height": 1096
            }
          },
          {
            "label": "Helpdesk",
            "heading": "Share self-serve resources",
            "body": "Empower clients to solve issues easily on their own with your Helpdesk. Create and share articles directly with clients, saving you time on support and cutting down on back-and-forth",
            "image": {
              "url": "/images/cms/5xgSW0sXvX9DkOwheJAmgb-helpdesk.webp",
              "alt": "Feature 3 / Helpdesk",
              "width": 2400,
              "height": 1096
            }
          },
          {
            "label": "Messaging",
            "heading": "Improve client communication",
            "body": "Make it easy for clients to reach out to your team with an optional live chat experience. Trigger email notifications to your team for maximum convenience and faster follow-up.",
            "image": {
              "url": "/images/cms/6g8rfnpP8hRrmhtSixofEC-messaging.webp",
              "alt": "Feature Tab 4 / Client Comms",
              "width": 2400,
              "height": 1096
            }
          }
        ],
        "quote": {
          "quote": "Assembly was the only one that let us flexibly build our own version of a client portal, uniting elements of their technology with existing external core applications that we wanted to keep using.",
          "name": "Kyle Pearson",
          "role": "Founder & CEO, Collective CPA",
          "href": "/customers/collective-cpa"
        }
      },
      {
        "kind": "features",
        "title": "Integrate with tools you already use",
        "description": "Embed services you already use with clients, from dashboard visualization tools to task management apps, and consolidate your client experience into one place.",
        "ctas": [],
        "image": {
          "url": "/images/cms/79iJkHO1qNZPwD4p6xJS1B-client_portal_integrations_vp_2.webp",
          "alt": "Platform VP 2 Embed",
          "width": 2400,
          "height": 1096
        }
      },
      {
        "kind": "features",
        "title": "Polished, branded client portals",
        "description": "Provide clients with an elevated, white-labeled, and professional experience with client-facing software that perfectly reflects your brand. Assembly makes it simple to build functional, branded agency client portals your customers will love.",
        "ctas": [],
        "features": [
          {
            "label": "Theme customization",
            "heading": "Theme customization",
            "body": "Customize your brand assets, typography, colors, and authentication experience.",
            "image": {
              "url": "/images/cms/5n08mrYI8OrHXFM1ve2kWO-custom_theme_assembly.webp",
              "alt": "Client Portal / Theme Customization",
              "width": 1224,
              "height": 1296
            }
          },
          {
            "label": "App and sidebar customization",
            "heading": "App and sidebar customization",
            "body": "Manage the order and visibility of tools you share with clients.",
            "image": {
              "url": "/images/cms/3FZPn8NOYQUcMeow90e5eW-app_sidebar_customization_assembly.webp",
              "alt": "App Sidebar customization",
              "width": 1224,
              "height": 1296
            }
          },
          {
            "label": "Custom domain and email domain",
            "heading": "Custom domain and email domain",
            "body": "Maintain brand consistency with a custom subdomain for your portal on your site.",
            "image": {
              "url": "/images/cms/6ONHDEgJxncgUIsU9kvcMx-custom_domain_assembly_square.webp",
              "alt": "Portal custom domain",
              "width": 1224,
              "height": 1296
            }
          }
        ]
      },
      {
        "kind": "grid",
        "title": "Finally, a frictionless client experience",
        "description": "Don’t force clients to remember another password or fumble with links. Assembly cuts the friction with passwordless authentication and lets clients reply by email, so they never have to log in just to connect with you.",
        "ctas": [],
        "items": [
          {
            "title": "Google SSO & Magic links",
            "description": "Once you create a client, you can instantly send invoices, forms, contracts, and more, allowing clients to complete actions seamlessly without a password.",
            "image": {
              "url": "/images/cms/2zt4ktrFi1lc5tpIofm9Vm-google_sso.webp",
              "alt": "SSO Google",
              "width": 924,
              "height": 760
            }
          },
          {
            "title": "Reply via eMail",
            "description": "If you message clients from the Assembly Dashboard, they’ll get an email notification and can reply directly from their inbox — no portal needed.",
            "image": {
              "url": "/images/cms/6Xfqfb5gDlamiKupWmzELg-reply_email.webp",
              "alt": "Reply by Email",
              "width": 924,
              "height": 760
            }
          }
        ]
      },
      {
        "kind": "grid",
        "title": "More than just a client portal",
        "ctas": [],
        "items": [
          {
            "title": "Invoicing",
            "description": "Create invoices for your clients to pay via credit card or ACH.",
            "href": "https://assembly.com/invoicing",
            "icon": {
              "url": "/images/cms/7EsKhlvePXmUA7oXkg3h9P-icon_invoicing.svg",
              "alt": "Icon / Invoicing"
            }
          },
          {
            "title": "Automations",
            "description": "Set up workflows that save you time with client management.",
            "href": "https://assembly.com/platform",
            "icon": {
              "url": "/images/cms/1flRTHSmPccu6P8zLbquBy-33.svg",
              "alt": "automation"
            }
          },
          {
            "title": "Subscriptions",
            "description": "Automate recurring payments and billing cycles for predictable revenue",
            "href": "https://assembly.com/guide/assembly-billing-app#subscriptions",
            "icon": {
              "url": "/images/cms/OduVerJi5FZcgOs7a2DAJ-subscription_app-icon.svg",
              "alt": "Subscriptions"
            }
          },
          {
            "title": "File-sharing",
            "description": "Share files and documents securely with easy client access and permissions.",
            "href": "https://assembly.com/file-sharing",
            "icon": {
              "url": "/images/cms/3ipz2j90k5hh1po2etisZV-file-sharing_app-icon.svg",
              "alt": "File-sharing"
            }
          },
          {
            "title": "Tasks",
            "description": "Manage tasks seamlessly across your team and clients in one place.",
            "href": "https://assembly.com/apps/directory/tasks",
            "icon": {
              "url": "/images/cms/63n3excnJirrH269FFqVYg-tasks_app-icon.svg",
              "alt": "Tasks"
            }
          },
          {
            "title": "Security",
            "description": "Keep data safe with enterprise-grade SOC 2 and HIPAA compliance.",
            "href": TRUST_CENTER_URL,
            "icon": {
              "url": "/images/cms/2z1KZwfUyLReXXIbaJNS0f-icon_-_security.svg",
              "alt": "Icon - Security"
            }
          },
          {
            "title": "CRM",
            "description": "Manage client relationships and track every interaction in one hub.",
            "href": "https://assembly.com/client-management",
            "icon": {
              "url": "/images/cms/un13D37gCMBXuvKbPG1k6-crm_app-icon.svg",
              "alt": "CRM"
            }
          },
          {
            "title": "Forms",
            "description": "Create custom intake forms to collect client information efficiently.",
            "href": "https://assembly.com/apps/directory/forms-app",
            "icon": {
              "url": "/images/cms/7bo7hIwcb0sUrJXbvbJ95O-forms_app-icon.svg",
              "alt": "Forms"
            }
          },
          {
            "title": "Contracts",
            "description": "Send professional agreements with built-in eSignatures.",
            "href": "https://assembly.com/esignature",
            "icon": {
              "url": "/images/cms/5J51JMXqLiyazZsh8RvvoH-contracts_app-icon.svg",
              "alt": "Contracts"
            }
          }
        ]
      },
      {
        "kind": "faq",
        "title": "Frequently asked questions",
        "items": [
          {
            "question": "What is a client portal?",
            "answer": "A client portal is a secure, online hub where businesses and their customers can communicate, share files, manage billing, and collaborate in real-time. Instead of using email, file-sharing, and various payment softwares, a client portal centralizes client communication into a single, branded environment—improving client experience, boosting efficiency, and ensuring data security. Assembly’s client portal software offers a comprehensive client experience and integrates seamlessly with your website and existing workflows."
          },
          {
            "question": "What features should I consider when choosing a client portal software?",
            "answer": "When selecting client portal software, look for features that enhance security, user experience, and business efficiency. Key features to prioritize include:\n- Secure messaging and file sharing\n- Custom branding and white-labeling\n- Integrated billing and e-signatures\n- Client onboarding workflows\n- Automations and integrations\n- Mobile accessibility\nAssembly offers all of the above in a beautifully designed, all-in-one platform built for modern client experiences."
          },
          {
            "question": "What makes Assembly’s client portal unique compared to others?",
            "answer": "Assembly stands out by offering a fully customizable, no-code client portal that combines sleek design with powerful functionality. Unlike generic portals, Assembly includes:\n• White-labeled branding, including custom domains and colors\n• Modular apps like messaging, billing, forms, and help desks\n• Seamless integrations with tools like Stripe, Zapier, and Airtable\n• Enterprise-grade security, including SOC 2 compliance and optional HIPAA compliance\nAssembly is built to elevate your client experience and scale with your business."
          },
          {
            "question": "Can Assembly's client portal be white-labeled?",
            "answer": "Yes, Assembly offers complete white-labeling options on Advanced and Professional plans. You can customize your client portal with your own logo, brand colors, and domain (e.g., portal.yourcompany.com), creating a fully branded experience that feels like an extension of your business. White-labeling enhances professionalism and builds trust with your clients."
          },
          {
            "question": "Is Assembly a no-code client portal or do I have to program?",
            "answer": "Yes, Assembly is a true no-code client portal platform. You don’t need any technical expertise or programming skills to set up, customize, or manage your portal. With an intuitive drag-and-drop interface and pre-built apps, you can launch a branded client experience in minutes—no developers needed."
          },
          {
            "question": "Does Assembly offer a secure client portal?",
            "answer": "Yes, Assembly’s client portal software offers enterprise-level data privacy and security for your client communications. Our platform is compliant with HIPAA, SOC 2, CCPA, and GDPR. For up to date reports on Assembly security compliance, visit our [Trust Center](https://security.assembly.com)."
          },
          {
            "question": "Does Assembly offer a HIPAA-compliant client portal?",
            "answer": "Yes, Assembly offers a HIPAA-compliant client portal option for organizations handling sensitive health data. With robust security infrastructure, audit controls, and custom administrative permissions, Assembly helps you meet HIPAA requirements while maintaining a user-friendly experience for your clients. For up-to-date proof of our compliance, visit our [Trust Center](https://security.assembly.com)."
          }
        ]
      }
    ],
    "closing": {
      "title": "Professional client portal software for modern businesses",
      "description": "Try for free, no credit card required.",
      "ctas": [
        {
          "label": "Get started",
          "href": SIGNUP_URL
        },
        {
          "label": "See pricing",
          "href": "/pricing"
        }
      ]
    }
  },
  {
    "slug": "store",
    "seo": {
      "title": "Shopify-style Stores for Professional Services",
      "description": "Create an online storefront for your services - made for marketing agencies, law firms, accounting firms, agencies, consultants, and more."
    },
    "noIndex": false,
    "hero": {
      "title": "Shopify-like stores for professional services",
      "description": "Productize your services with storefronts and let clients self-serve purchase subscription plans and one-time items.",
      "ctas": [
        {
          "label": "Get started",
          "href": SIGNUP_URL
        }
      ],
      "image": {
        "url": "/images/cms/5lVsM8VMXQfL20K1GCqiUS-checkout.webp",
        "alt": "Checkout Store Tab 1",
        "width": 2400,
        "height": 1513
      },
      "layout": "center"
    },
    "sections": [
      {
        "kind": "features",
        "title": "Attract clients who pay you upfront",
        "description": "Skip the back-and-forth email threads. Standardize your rates with an online store and find clients who know what they want and will pay you for it.",
        "ctas": [],
        "features": [
          {
            "label": "Store",
            "heading": "Online storefront for self-serve purchases",
            "body": "New customers can purchase one-time or recurring services from your store like they would shop for eCommerce products. Gaining recurring revenue just got easier.",
            "image": {
              "url": "/images/cms/5lVsM8VMXQfL20K1GCqiUS-checkout.webp",
              "alt": "Checkout Store Tab 1",
              "width": 2400,
              "height": 1513
            }
          },
          {
            "label": "Billing",
            "heading": "Easy checkout on web and mobile",
            "body": "Take credit card payments and bank payments through secure checkout available on all devices.",
            "image": {
              "url": "/images/cms/42Sw8RlFNlmD0XrGKmERqa-checkout__1_.webp",
              "alt": "Checkout Billing Store",
              "width": 2400,
              "height": 1513
            }
          },
          {
            "label": "Onboarding",
            "heading": "From checkout to seamless onboarding",
            "body": "New clients who make their first purchase are seamlessly transitioned to your client portal — a space where they can submit forms, sign contracts, access resources, and more.",
            "image": {
              "url": "/images/cms/wYejTmosLzlR4zQMPOKKY-checkout__2_.webp",
              "alt": "Checkout 3 To Client Portal Store",
              "width": 2400,
              "height": 1513
            }
          }
        ]
      },
      {
        "kind": "features",
        "title": "Bring the best of eCommerce to your firm",
        "description": "Join the league of modern businesses who “productize” their services. Customize your offerings with details and packaging that make you stand out from the competition.",
        "ctas": [],
        "features": [
          {
            "label": "Subscriptions & Products",
            "heading": "Add subscriptions & one-time purchases",
            "body": "Offer services as either one-time products or recurring plans with custom billing schedules.",
            "image": {
              "url": "/images/cms/4jNueWLVR7VoPYi8J4lQY4-iu_experience_store.webp",
              "alt": "IU Experience Store",
              "width": 2400,
              "height": 1491
            }
          },
          {
            "label": "Custom visibility",
            "heading": "Customize visibility for your store",
            "body": "Control if your store is available only in your client portal or published on a public page.",
            "image": {
              "url": "/images/cms/17JV8CiL3tvkpThigLx8Tz-store_privacy_public.webp",
              "alt": "Store Privacy Public",
              "width": 2400,
              "height": 1490
            }
          }
        ]
      },
      {
        "kind": "features",
        "title": "Onboard clients seamlessly after purchases and payments",
        "description": "Onboard and engage clients who buy from you with integrated client portal software that keeps them immersed in your brand.",
        "ctas": [],
        "image": {
          "url": "/images/cms/4FCpOdR1dse2DfYhQsUDfk-image.webp",
          "alt": "Store to onboarding",
          "width": 2400,
          "height": 986
        }
      },
      {
        "kind": "grid",
        "title": "More than just a storefront",
        "description": "Deliver a delightful client experience with powerful tools included at no extra cost — a branded client portal, messaging, file-sharing, invoicing and more.",
        "ctas": [],
        "items": [
          {
            "title": "Client portal",
            "description": "Give clients access to messages, contracts, files, and more.",
            "href": "https://assembly.com/client-portal",
            "icon": {
              "url": "/images/cms/1PkNte2UVDmgRgv39rXEj0-client-portal_app-icon.svg",
              "alt": "Client portal"
            }
          },
          {
            "title": "Invoicing",
            "description": "Create invoices for your clients to pay via credit card or ACH.",
            "href": "https://assembly.com/invoicing",
            "icon": {
              "url": "/images/cms/7EsKhlvePXmUA7oXkg3h9P-icon_invoicing.svg",
              "alt": "Icon / Invoicing"
            }
          },
          {
            "title": "Subscriptions",
            "description": "Automate recurring payments and billing cycles for predictable revenue",
            "href": "https://assembly.com/guide/assembly-billing-app#subscriptions",
            "icon": {
              "url": "/images/cms/OduVerJi5FZcgOs7a2DAJ-subscription_app-icon.svg",
              "alt": "Subscriptions"
            }
          },
          {
            "title": "File-sharing",
            "description": "Share files and documents securely with easy client access and permissions.",
            "href": "https://assembly.com/file-sharing",
            "icon": {
              "url": "/images/cms/3ipz2j90k5hh1po2etisZV-file-sharing_app-icon.svg",
              "alt": "File-sharing"
            }
          },
          {
            "title": "Tasks",
            "description": "Manage tasks seamlessly across your team and clients in one place.",
            "href": "https://assembly.com/apps/directory/tasks",
            "icon": {
              "url": "/images/cms/63n3excnJirrH269FFqVYg-tasks_app-icon.svg",
              "alt": "Tasks"
            }
          },
          {
            "title": "Security",
            "description": "Keep data safe with enterprise-grade SOC 2 and HIPAA compliance.",
            "href": TRUST_CENTER_URL,
            "icon": {
              "url": "/images/cms/2z1KZwfUyLReXXIbaJNS0f-icon_-_security.svg",
              "alt": "Icon - Security"
            }
          },
          {
            "title": "CRM",
            "description": "Manage client relationships and track every interaction in one hub.",
            "href": "https://assembly.com/client-management",
            "icon": {
              "url": "/images/cms/un13D37gCMBXuvKbPG1k6-crm_app-icon.svg",
              "alt": "CRM"
            }
          },
          {
            "title": "Forms",
            "description": "Create custom intake forms to collect client information efficiently.",
            "href": "https://assembly.com/apps/directory/forms-app",
            "icon": {
              "url": "/images/cms/7bo7hIwcb0sUrJXbvbJ95O-forms_app-icon.svg",
              "alt": "Forms"
            }
          },
          {
            "title": "Contracts",
            "description": "Send professional agreements with built-in eSignatures.",
            "href": "https://assembly.com/esignature",
            "icon": {
              "url": "/images/cms/5J51JMXqLiyazZsh8RvvoH-contracts_app-icon.svg",
              "alt": "Contracts"
            }
          }
        ]
      },
      {
        "kind": "faq",
        "title": "Frequently asked questions",
        "items": [
          {
            "question": "What does it mean to productize a service?",
            "answer": "[Productizing a service](https://assembly.com/blog/productized-service-business-model) is when a business turns a service that would normally quoted by hour or by retainer into a package with specific features, prices, and timelines that customers can purchase like they would purchase a product."
          },
          {
            "question": "What is the best way to sell services online?",
            "answer": "You can list services online on a website, but the best way to sell services is to offer a way for people to purchase them without having to contact you first. An online storefront like Assembly lets service businesses create Shopify style stores that are optimized for providing professional services to clients."
          },
          {
            "question": "How do I set up my online store for my services?",
            "answer": "The easiest way to set up an online store for your professional services is with Assembly. Assembly’s store lets you create and customize one-time services, recurring packages, and subscriptions. What’s more, clients who buy services are automatically created in your custom branded client portal, allowing you to manage their communications, billing, and invoices in one place."
          },
          {
            "question": "How do I know who buys from my online store?",
            "answer": "With Assembly Stores, people who purchase from your store page will automatically become clients in your CRM that you can manage. Their information comes from their purchase information and is collected and saved in your secure client portal. They also get access to your portal for onboarding and contacting you right after checkout."
          },
          {
            "question": "Can I make a private online store?",
            "answer": "Yes, with Assembly stores, you can create a private online store that is only visible to clients who log in via a secure client portal. You can invite clients to join via a link or email."
          },
          {
            "question": "Can I connect my store to my existing website?",
            "answer": "Yes, with Assembly Store, you can publish a public link to your online store that lets you link to it from an existing website or share via email or social media. We will soon release the ability for you to embed the store in an iFrame on your site."
          },
          {
            "question": "How does Assembly’s store compare to Shopify?",
            "answer": "Unlike Shopify stores, Assembly stores are built for businesses selling professional services, not consumer products. When you launch a Assembly store, you can offer custom recurring plans and one-off service items and then immediately have clients paying and onboarded through your client portal software."
          }
        ]
      }
    ],
    "closing": {
      "title": "Package your expertise. Productize your services.",
      "description": "Try for free, no credit card required.",
      "ctas": [
        {
          "label": "Get started",
          "href": SIGNUP_URL
        },
        {
          "label": "See pricing",
          "href": "/pricing"
        }
      ]
    }
  },
  {
    "slug": "esignature",
    "seo": {
      "title": "Electronic Signature Software for Service Firms",
      "description": "Send, sign, and manage contracts securely with branded electronic signature software built for professional firms. Try Assembly free."
    },
    "noIndex": false,
    "hero": {
      "title": "Electronic signature software for service firms",
      "description": "Easy contract management platform for service-based businesses. Create docs and request electronic signatures in a seamlessly branded client portal. Try for free – no credit card required.",
      "ctas": [
        {
          "label": "Start for free",
          "href": SIGNUP_URL
        }
      ],
      "image": {
        "url": "/images/cms/6YEOJATfZo1nCtbD7pRtxx-image.webp",
        "alt": "Hero Image / Contracts 06/05/25",
        "width": 958,
        "height": 1267
      },
      "layout": "left"
    },
    "sections": [
      {
        "kind": "features",
        "title": "Deliver fast, secure, and client-friendly contracts.",
        "description": "Professional digital signature and electronic signature tools designed for teams who need reliability, security, and speed. Send mobile-friendly documents online seamlessly with a fully branded portal.",
        "ctas": [],
        "features": [
          {
            "label": "Contracts",
            "heading": "Elevate your client experience with a branded eSignature tool.",
            "body": "Give clients a DocuSign alternative that offers them a unified, professional experience under your brand.",
            "image": {
              "url": "/images/cms/1lKsyJiXmXai7q50xVgTBO-contracts-esignature2.webp",
              "alt": "Feature 2 Image / Contracts Esignature",
              "width": 2300,
              "height": 1450
            }
          }
        ]
      },
      {
        "kind": "grid",
        "title": "A professional tool for professional firms",
        "description": "Secure data with enterprise-grade safeguards (SOC2, HIPAA), and trigger actions with APIs and webhooks. Export audit trails, automate contract workflows, and personalize the experience with branding and a custom domain.",
        "ctas": [],
        "items": [
          {
            "title": "Audit trails",
            "description": "Audit trails provide proof of contract access, review, and signature.",
            "icon": {
              "url": "/images/cms/1TlnUB9fUaYCTwN5XxPl17-icon_-_grayscale_-_roadmap.svg",
              "alt": "Icon - Grayscale - Roadmap"
            }
          },
          {
            "title": "Templates",
            "description": "Create reusables templates with autofill fields and variable fields.",
            "icon": {
              "url": "/images/cms/1i8BKOm82JlDodqvFtlxGI-icon_-_copy.svg",
              "alt": "Icon - templates"
            }
          },
          {
            "title": "Branded signing",
            "description": "Provide clients a completely white-label signing experience.",
            "icon": {
              "url": "/images/cms/1JciTicoaxJAxyMFGiJj0s-icon_-_branded_invoices.svg",
              "alt": "Icon - Branded invoices"
            }
          },
          {
            "title": "Security",
            "description": "Stay compliant with SOC2 and HIPAA compliance.",
            "icon": {
              "url": "/images/cms/1TlnUB9fUaYCTwN5XxPl17-icon_-_grayscale_-_roadmap.svg",
              "alt": "Icon - Grayscale - Roadmap"
            }
          },
          {
            "title": "Contracts API",
            "description": "Assign contracts to clients and use contracts submission data in workflows.",
            "icon": {
              "url": "/images/cms/1TlnUB9fUaYCTwN5XxPl17-icon_-_grayscale_-_roadmap.svg",
              "alt": "Icon - Grayscale - Roadmap"
            }
          },
          {
            "title": "Automations",
            "description": "Use our internal automations feature to assign contracts as part of workflows.",
            "icon": {
              "url": "/images/cms/1flRTHSmPccu6P8zLbquBy-33.svg",
              "alt": "automation"
            }
          },
          {
            "title": "Zapier and Make",
            "description": "Use no-code tools like Zapier and Make for contract automation workflows.",
            "icon": {
              "url": "/images/cms/1TlnUB9fUaYCTwN5XxPl17-icon_-_grayscale_-_roadmap.svg",
              "alt": "Icon - Grayscale - Roadmap"
            }
          },
          {
            "title": "Exports",
            "description": "Seamlessly exports contracts in PDF and contract analytics reports in CSV.",
            "icon": {
              "url": "/images/cms/1TlnUB9fUaYCTwN5XxPl17-icon_-_grayscale_-_roadmap.svg",
              "alt": "Icon - Grayscale - Roadmap"
            }
          }
        ]
      },
      {
        "kind": "features",
        "title": "Streamlined contract management",
        "description": "Simplify your contract management process with tools designed to save time and boost efficiency. Create one-time eSignature requests, manage and track contracts easily, and set up reusable contract templates that can be configured as part of automated workflows.",
        "ctas": [],
        "features": [
          {
            "label": "Contract creation",
            "heading": "Create contracts or upload templates",
            "body": "Create unlimited contracts and contract templates by uploading a PDF and adding your inputs, clients inputs, autofill fields, and more.",
            "image": {
              "url": "/images/cms/4ZzEY5oKj7iX7By8vsEWFG-contract-creation.webp",
              "alt": "Feature Tab 1 / Contract Creation",
              "width": 2010,
              "height": 1246
            }
          },
          {
            "label": "Contract management",
            "heading": "Manage your contracts",
            "body": "Manage contracts, spot overdue contract requests, view contract analytics, and export data.",
            "image": {
              "url": "/images/cms/72gyK2vsqmROopf73SHpOp-contract-management.webp",
              "alt": "Feature Tab 2 / Contract Management",
              "width": 2010,
              "height": 1246
            }
          },
          {
            "label": "Notifications",
            "heading": "Get notified to all important client activity",
            "body": "Get notified when contracts are signed in a unified notification center that informs you about all important client activity.",
            "image": {
              "url": "/images/cms/2oM7J6RzUO1y3Ck1hD5MyX-unified-notification.webp",
              "alt": "Feature Tab 3 / Unified notifications",
              "width": 2010,
              "height": 1246
            }
          }
        ]
      },
      {
        "kind": "grid",
        "title": "More than just eSignatures",
        "description": "Seamlessly grow beyond contracts. Automate your entire client journey with powerful tools included at no extra cost — invoicing, subscription billing, intake forms, file-sharing, and more.",
        "ctas": [
          {
            "label": "Get started",
            "href": SIGNUP_URL
          }
        ],
        "items": [
          {
            "title": "Invoicing",
            "description": "Create invoices for your clients to pay via credit card or ACH.",
            "href": "https://assembly.com/invoicing",
            "icon": {
              "url": "/images/cms/7EsKhlvePXmUA7oXkg3h9P-icon_invoicing.svg",
              "alt": "Icon / Invoicing"
            }
          },
          {
            "title": "Automations",
            "description": "Set up workflows that save you time with client management.",
            "href": "https://assembly.com/platform",
            "icon": {
              "url": "/images/cms/1flRTHSmPccu6P8zLbquBy-33.svg",
              "alt": "automation"
            }
          },
          {
            "title": "Subscriptions",
            "description": "Automate recurring payments and billing cycles for predictable revenue",
            "href": "https://assembly.com/guide/assembly-billing-app#subscriptions",
            "icon": {
              "url": "/images/cms/OduVerJi5FZcgOs7a2DAJ-subscription_app-icon.svg",
              "alt": "Subscriptions"
            }
          },
          {
            "title": "File-sharing",
            "description": "Share files and documents securely with easy client access and permissions.",
            "href": "https://assembly.com/file-sharing",
            "icon": {
              "url": "/images/cms/3ipz2j90k5hh1po2etisZV-file-sharing_app-icon.svg",
              "alt": "File-sharing"
            }
          },
          {
            "title": "Tasks",
            "description": "Manage tasks seamlessly across your team and clients in one place.",
            "href": "https://assembly.com/apps/directory/tasks",
            "icon": {
              "url": "/images/cms/63n3excnJirrH269FFqVYg-tasks_app-icon.svg",
              "alt": "Tasks"
            }
          },
          {
            "title": "Security",
            "description": "Keep data safe with enterprise-grade SOC 2 and HIPAA compliance.",
            "href": TRUST_CENTER_URL,
            "icon": {
              "url": "/images/cms/2z1KZwfUyLReXXIbaJNS0f-icon_-_security.svg",
              "alt": "Icon - Security"
            }
          },
          {
            "title": "CRM",
            "description": "Manage client relationships and track every interaction in one hub.",
            "href": "https://assembly.com/client-management",
            "icon": {
              "url": "/images/cms/un13D37gCMBXuvKbPG1k6-crm_app-icon.svg",
              "alt": "CRM"
            }
          },
          {
            "title": "Forms",
            "description": "Create custom intake forms to collect client information efficiently.",
            "href": "https://assembly.com/apps/directory/forms-app",
            "icon": {
              "url": "/images/cms/7bo7hIwcb0sUrJXbvbJ95O-forms_app-icon.svg",
              "alt": "Forms"
            }
          },
          {
            "title": "Contracts",
            "description": "Send professional agreements with built-in eSignatures.",
            "href": "https://assembly.com/esignature",
            "icon": {
              "url": "/images/cms/5J51JMXqLiyazZsh8RvvoH-contracts_app-icon.svg",
              "alt": "Contracts"
            }
          }
        ]
      },
      {
        "kind": "faq",
        "title": "Frequently asked questions",
        "items": [
          {
            "question": "What is an electronic signature and digital signature?",
            "answer": "Electronic signatures (eSignatures): a more general term for fast and secure ways to sign online agreements. It usually includes needing to do actions like typing your name and uploading your signature, and can include drawing a signature with a mouse or finger.\n\nDigital signatures: a more specific term than eSignature, which has an extra layer of security. Usually, this happens via encryption and identity verification. Most advanced eSignature tools, such as Assembly, use digital signature technology to keep your documents compliant and secure."
          },
          {
            "question": "Are eSignatures legally enforceable?",
            "answer": "Yes. eSignatures are legally enforceable and valid in most countries, such as the U.S. and countries within the EU.\n\nWhen a client signs a contract in Assembly, it includes a full audit trail; you will have clear proof of who signed what, when they signed it, and where they were when it happened."
          },
          {
            "question": "What types of documents can be signed electronically?",
            "answer": "You can use Assembly to sign things the following: client agreements (like MSAs and SOWs), freelance or contractor agreements, NDAs, proposals, onboarding forms, and more.\n\nIf you can upload it as a PDF, you can sign it with Assembly."
          },
          {
            "question": "What document formats do Assembly contracts support?",
            "answer": "Assembly supports PDF contracts. This keeps your formatting consistent across devices and is the industry standard digital signatures."
          },
          {
            "question": "How do recipients sign Assembly contracts?",
            "answer": "Clients receive a contract directly through your branded client portal or via email. No logins or downloads are required in order to sign. Just click, review, and sign. Signing the contract is easy to do and optimized for desktop and mobile."
          },
          {
            "question": "How do I know if a recipient has signed a contract?",
            "answer": "You will get updated when your client signs a contract. You'll see the updated contract status in your dashboard as soon as it's signed. Your client can also view a final copy of the signed contract in their portal."
          },
          {
            "question": "How is Assembly different from DocuSign, HelloSign, PandaDoc, and others?",
            "answer": "Assembly isn’t just for contracts—it is a full client experience platform complete with a CRM and client portal.\n\nTools like DocuSign focus solely on signatures, but Assembly brings together contracts, payments, messaging, forms, file-sharing, and more into one client portal.\n\nAssembly's Advanced plan is white-labeled, so your brand stays front and center—on your domain, in your emails, and throughout the client experience.\n\nYour clients get one simple login for everything. You get a streamlined, professional workflow that scales."
          }
        ]
      }
    ],
    "closing": {
      "title": "Modern eSignatures for professional service businesses",
      "description": "Try for free, no credit card required.",
      "ctas": [
        {
          "label": "Get started",
          "href": SIGNUP_URL
        },
        {
          "label": "See pricing",
          "href": "/pricing"
        }
      ]
    }
  },
  {
    "slug": "platform",
    "seo": {
      "title": "No-Code Client Portal Software",
      "description": "Assembly’s no-code client portal software is SOC 2 and HIPAA compliant, with 100+ integrations and automations to power secure client experiences."
    },
    "noIndex": false,
    "hero": {
      "title": "The most flexible client portal platform",
      "description": "Integrate powerful workflow automations, custom business software and more on a secure client portal.",
      "ctas": [
        {
          "label": "Get started",
          "href": SIGNUP_URL
        },
        {
          "label": "Book a demo",
          "href": DEMO_URL
        }
      ],
      "image": {
        "url": "/images/cms/2Gc21Wg7DtXhUwIofgll70-no_shadow_2.webp",
        "alt": "Platform Hero",
        "width": 2400,
        "height": 1149
      },
      "layout": "center"
    },
    "sections": [
      {
        "kind": "features",
        "title": "Build custom integrations and apps",
        "description": "Use our API to build custom integrations or create full applications inside the client portal. Work with our expert partners for tailored solutions.",
        "ctas": [
          {
            "label": "View the API docs",
            "href": GUIDE_URL
          }
        ],
        "quote": {
          "quote": "Assembly saves us from coding a whole portal solution. We implemented a HIPAA-compliant customer portal quickly.",
          "name": "Robert Prochnow",
          "role": "Founder, Zen Aegis",
          "href": "/customers/zen-aegis"
        },
        "image": {
          "url": "/images/cms/6hAvadX0vy42wKu25uHdig-platform_code.webp",
          "alt": "Platform VP 1 Code",
          "width": 2400,
          "height": 1096
        }
      },
      {
        "kind": "features",
        "title": "Embed your favorite tools as easily as installing apps",
        "description": "Keep workflows seamless by embedding your existing tools directly in the client portal. From analytics dashboards to project trackers, Assembly brings everything into one view.",
        "ctas": [
          {
            "label": "View App Store",
            "href": "https://assembly.com/apps/directory"
          }
        ],
        "image": {
          "url": "/images/cms/79iJkHO1qNZPwD4p6xJS1B-client_portal_integrations_vp_2.webp",
          "alt": "Platform VP 2 Embed",
          "width": 2400,
          "height": 1096
        }
      },
      {
        "kind": "features",
        "title": "Extend without code",
        "description": "Build workflows that automate client onboarding, file sharing, invoicing, and more, no developer required. Connect Assembly to 1,000+ apps with Zapier, Make, and other no-code tools.",
        "ctas": [],
        "image": {
          "url": "/images/cms/3WNAV9RNkJElvugXehl0iw-automations.webp",
          "alt": "Platform VP 3 Automations",
          "width": 2400,
          "height": 1096
        }
      },
      {
        "kind": "grid",
        "title": "More tools for custom development",
        "description": "Deliver a bespoke client experience with a flexible development platform, from no-code to code.",
        "ctas": [
          {
            "label": "View Documentation",
            "href": GUIDE_URL
          },
          {
            "label": "Book a demo",
            "href": DEMO_URL
          }
        ],
        "items": [
          {
            "title": "Security & Compliance",
            "description": "Features for SOC 2, HIPAA compliant portals built-in.",
            "href": TRUST_CENTER_URL
          },
          {
            "title": "Zapier + Make integrations",
            "description": "Use third-party workflow automation tools to enhance your client experience."
          },
          {
            "title": "API for technical development",
            "description": "Access our API to build advanced features and integrations.",
            "href": GUIDE_URL,
            "icon": {
              "url": "/images/cms/4wkDV6FtsilzBuAjfab0i7-hardware.svg",
              "alt": "Icon - home-outline5"
            }
          },
          {
            "title": "Custom applications",
            "description": "Connect with the team to discuss creating custom applications.",
            "href": DEMO_URL,
            "icon": {
              "url": "/images/cms/57aoJSfqcz3GYQ9vY63jVi-icon_-_home-outline.svg",
              "alt": "image"
            }
          },
          {
            "title": "Hire expert developers",
            "description": "Contract with experts to build and manage your portal.",
            "href": "https://assembly.com/experts",
            "icon": {
              "url": "/images/cms/3d4lw8JNrgDT5Fv31L71UV-find-an-expert-icon.svg",
              "alt": "Navbar - Find an Expert Icon"
            }
          }
        ]
      }
    ],
    "closing": {
      "title": "Develop on a flexible platform for customer experience.",
      "description": "Try Assembly for free, no credit card required.",
      "ctas": [
        {
          "label": "Get started",
          "href": SIGNUP_URL
        },
        {
          "label": "Book a demo",
          "href": DEMO_URL
        }
      ]
    }
  }
];
