// 3 frozen pages: the job listings, as Contentful held them the day
// they were taken out of it. This file IS the source — there is no CMS read
// behind it any more, so a copy change is an edit here and a deploy.
//
// Generated by scripts/freeze-cms.mts. Regenerating overwrites hand edits, so
// once you start editing the copy here, stop regenerating: the CMS entries are
// no longer maintained. Imagery lives in public/images/cms, downloaded with it.
import type { JobListing } from "./careers";

export const FROZEN_JOB_LISTINGS = [
  {
    "slug": "junior-technical-support-specialist",
    "name": "Junior Technical Support Specialist",
    "department": "Support",
    "description": {
      "data": {},
      "content": [
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [],
              "value": "About the role",
              "nodeType": "text"
            }
          ],
          "nodeType": "heading-2"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [],
              "value": "This is an entry-level role that has a flexible location. You’ll join our small but mighty Support + Success team, the friendly tech superheroes who make sure our customers are happy, successful, and never stuck. You’ll tackle customer issues — think accounts, billing, subscriptions, and minor technical hiccups — while learning the ins and outs of our platform. You will become a product expert and be able to address questions that cover existing capabilities and future roadmap features. Over time, you’ll get better at solving more complex problems and become a go-to expert for our users.",
              "nodeType": "text"
            }
          ],
          "nodeType": "paragraph"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [],
              "value": "",
              "nodeType": "text"
            }
          ],
          "nodeType": "paragraph"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [],
              "value": "Who you are",
              "nodeType": "text"
            }
          ],
          "nodeType": "heading-2"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "You are a recent college graduate or graduated from a technical bootcamp.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "You thrive in a technical environment and love helping people solve problems.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Quick on your feet and a fast learner—you enjoy figuring things out as you go.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Tech-savvy and comfortable jumping between tools and systems. Extra points if you’ve played with AWS, Dynamo, Retool, or Front.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Clear and empathetic communicator—you can explain tricky stuff without jargon.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Interested or experienced in working with APIs, databases, and no-code integrations like Retool; Stripe experience is a nice bonus.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "You care about users and genuinely want to make their day a little easier.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            }
          ],
          "nodeType": "unordered-list"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [],
              "value": "What you'll do",
              "nodeType": "text"
            }
          ],
          "nodeType": "heading-2"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Spend most of your time helping customers — solving issues, answering questions, and keeping them smiling.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Partner with your Support + Success Lead and other teams to tackle tricky problems and find solutions.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Assist with creating and troubleshooting automations through Make and Zapier as well as native Assembly automation workflows.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Translate technical issues into plain language for our customers—no jargon allowed.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Gather info, report bugs, and work with Engineering to improve the product.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Resolve support issues within our SLA agreements, including internal and client accounts, billing and subscriptions, and minor technical issues.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Build a deep understanding of our technical architecture and grow your ability to diagnose and resolve more complex problems.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            }
          ],
          "nodeType": "unordered-list"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [],
              "value": "Why you’ll love it here",
              "nodeType": "text"
            }
          ],
          "nodeType": "heading-2"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "You’ll have real impact on how our customers succeed.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Work with a tight-knit, friendly team who loves collaboration and creativity.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Plenty of room to grow and level up your skills as our company scales.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            }
          ],
          "nodeType": "unordered-list"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [],
              "value": "",
              "nodeType": "text"
            }
          ],
          "nodeType": "paragraph"
        }
      ],
      "nodeType": "document"
    },
    "team": [
      {
        "name": "Brittany Nickell",
        "profileLink": "https://www.linkedin.com/in/brittanyleighnickell/",
        "image": {
          "url": "/images/cms/6Wtzv2ER7HK1wujQne8v1c-britt.webp",
          "alt": "Brittany Nickell"
        }
      },
      {
        "name": "Veronique Cadet",
        "profileLink": "https://www.linkedin.com/in/v%C3%A9roniquecadet/",
        "image": {
          "url": "/images/cms/3aoCGbZrlalK0pR7WTr8Yo-ver.webp",
          "alt": "Veronique Cadet"
        }
      }
    ]
  },
  {
    "slug": "account-executive",
    "name": "Account Executive",
    "department": "Sales",
    "description": {
      "data": {},
      "content": [
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [
                {
                  "type": "bold"
                }
              ],
              "value": "About the role",
              "nodeType": "text"
            }
          ],
          "nodeType": "heading-2"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [],
              "value": "As an Account Executive you will report to the CEO and join our two-person sales team. In this role you’ll run a high-velocity sales motion end-to-end — qualifying leads, running demos, and closing deals. You’ll sell to a wide range of service-based businesses (startups, accounting firms, law firms, agencies, and more), so strong discovery and solutioning matters a lot.",
              "nodeType": "text"
            }
          ],
          "nodeType": "paragraph"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [],
              "value": "We’re post-PMF with 1,000+ paying customers, and our sales lead exceeded quota last quarter. We’ll compensate you well, invest deeply in your development, and give you the opportunity to help define our sales process, systems, and tooling as we scale.",
              "nodeType": "text"
            }
          ],
          "nodeType": "paragraph"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [],
              "value": "What you'll do",
              "nodeType": "text"
            }
          ],
          "nodeType": "heading-2"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You'll run demos and close deals.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You’ll do 5+ demos per day, handle objections, and consistently move deals from first call to close.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You'll lead discovery and solutioning.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You’ll understand customer workflows and pain points, map them to our product, and propose clear solutions across industries and use cases.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You'll own your pipeline.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You’ll stay on top of follow-ups, next steps, multi-threading, and deal hygiene. You’ll keep forecasts accurate and momentum high.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You'll sell value at meaningful price points.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You’ll be comfortable closing deals in the ~$2,500–$50k/year range and communicating ROI clearly.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You'll become an expert in our product.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You’ll develop deep product fluency — features, positioning, edge cases—and continually sharpen your demo and narrative as the product evolves.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You'll collaborate tightly with product and the broader team.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You’ll bring crisp feedback from the field — what’s confusing, what’s missing, what’s resonating — and contribute beyond sales (product feedback, marketing, success, etc.).",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You'll help build the machine.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " Early sales is messy. You’ll help define the playbook: messaging, qualification, demo flow, CRM workflows, enablement, tooling, and reporting.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            }
          ],
          "nodeType": "unordered-list"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [],
              "value": "Who you are",
              "nodeType": "text"
            }
          ],
          "nodeType": "heading-2"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You're experienced.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You’ve sold in early-to-mid stage startups where you had to be scrappy, self-directed, and willing to get your hands dirty.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You're a closer.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You have a track record of hitting quota and running deals through the finish line in a high-velocity environment.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You're great at solutioning.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You ask sharp questions, listen closely, and can translate messy customer problems into a clear plan and a confident recommendation.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You're experienced selling to our ICP.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You’ve sold B2B software to service-based businesses — e.g., marketing agencies, accounting firms, law firms, consultancies, and other tech-enabled professional services teams. You understand how owners/operators buy, what they care about, and how to build urgency without being pushy.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You're comfortable with technical concepts.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You don’t have to be an engineer, but you should be comfortable discussing concepts like automation workflows, embeddings, no-code tooling, and modern software systems without getting lost.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You communicate clearly.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " Your demos are organized and compelling. Your follow-ups are crisp. You don’t ramble, and you don’t hide the ball.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You're competitive and candid.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You like direct feedback, you want to win, and you thrive in a performance culture that’s high-trust and high-expectations.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You're hardworking.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " You understand that building a category-defining company requires people that work smart and that also work hard.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "value": "You love working in person.",
                      "nodeType": "text"
                    },
                    {
                      "data": {},
                      "marks": [],
                      "value": " We're convinced that building a strong culture happens face-to-face, and we're looking for people who thrive in highly collaborative, in-person environments.",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            }
          ],
          "nodeType": "unordered-list"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [],
              "value": "Sales stack",
              "nodeType": "text"
            }
          ],
          "nodeType": "heading-2"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Salesforce",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Sybill",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Retool",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            },
            {
              "data": {},
              "content": [
                {
                  "data": {},
                  "content": [
                    {
                      "data": {},
                      "marks": [],
                      "value": "Chili Piper",
                      "nodeType": "text"
                    }
                  ],
                  "nodeType": "paragraph"
                }
              ],
              "nodeType": "list-item"
            }
          ],
          "nodeType": "unordered-list"
        },
        {
          "data": {},
          "content": [
            {
              "data": {},
              "marks": [],
              "value": "",
              "nodeType": "text"
            }
          ],
          "nodeType": "paragraph"
        }
      ],
      "nodeType": "document"
    },
    "team": [
      {
        "name": "Marlon Misra",
        "profileLink": "https://www.linkedin.com/in/marlonmisra/",
        "image": {
          "url": "/images/cms/467AAyP0ueqdADoYTy63hR-pp.webp",
          "alt": "Marlon Misra"
        }
      },
      {
        "name": "Brittany Nickell",
        "profileLink": "https://www.linkedin.com/in/brittanyleighnickell/",
        "image": {
          "url": "/images/cms/6Wtzv2ER7HK1wujQne8v1c-britt.webp",
          "alt": "Brittany Nickell"
        }
      },
      {
        "name": "Sean Walsh",
        "profileLink": "https://www.linkedin.com/in/seanwalshnyc/",
        "image": {
          "url": "/images/cms/mn6yQCTnVVBh9YVmqbWf5-screenshot_2024-08-07_at_2.11.11_pm.webp",
          "alt": "Team - Sean"
        }
      }
    ]
  },
  {
    "slug": "senior-software-engineer-core-product",
    "name": "Senior Software Engineer",
    "department": "Engineering",
    "description": {
      "nodeType": "document",
      "data": {},
      "content": [
        {
          "nodeType": "heading-2",
          "data": {},
          "content": [
            {
              "nodeType": "text",
              "value": "About the role",
              "marks": [],
              "data": {}
            }
          ]
        },
        {
          "nodeType": "paragraph",
          "data": {},
          "content": [
            {
              "nodeType": "text",
              "value": "As a senior software engineer you will report to the CTO and be a core member of our engineering and product team. In this role you’ll lead complex technical projects, mentor junior team members, improve velocity through better process, shape the engineering roadmap, and help define our engineering culture. We will compensate you well, invest deeply in your development, and do everything we can to make sure this is the single best work experience of your life.",
              "marks": [],
              "data": {}
            }
          ]
        },
        {
          "nodeType": "heading-2",
          "data": {},
          "content": [
            {
              "nodeType": "text",
              "value": "What you'll do",
              "marks": [],
              "data": {}
            }
          ]
        },
        {
          "nodeType": "unordered-list",
          "data": {},
          "content": [
            {
              "nodeType": "list-item",
              "data": {},
              "content": [
                {
                  "nodeType": "paragraph",
                  "data": {},
                  "content": [
                    {
                      "nodeType": "text",
                      "value": "You'll design and build full stack features. ",
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "data": {}
                    },
                    {
                      "nodeType": "text",
                      "value": "You'll be working on scaling and enhancing our web platform, our flagship product. This involves overseeing the libraries we use, managing the component/design system architecture, and building the most robust testable features.",
                      "marks": [],
                      "data": {}
                    }
                  ]
                }
              ]
            },
            {
              "nodeType": "list-item",
              "data": {},
              "content": [
                {
                  "nodeType": "paragraph",
                  "data": {},
                  "content": [
                    {
                      "nodeType": "text",
                      "value": "You'll be an owner. ",
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "data": {}
                    },
                    {
                      "nodeType": "text",
                      "value": "You'll work with EPD (engineering/product/design) leads team to help shape the roadmap. You’ll also be responsible for writing technical documentation, setting up infrastructure, and organizing engineering tasks.",
                      "marks": [],
                      "data": {}
                    }
                  ]
                }
              ]
            },
            {
              "nodeType": "list-item",
              "data": {},
              "content": [
                {
                  "nodeType": "paragraph",
                  "data": {},
                  "content": [
                    {
                      "nodeType": "text",
                      "value": "You'll balance the short and long term. ",
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "data": {}
                    },
                    {
                      "nodeType": "text",
                      "value": "While knowing the importance of shipping quickly you also know how to craft thoughtful long-term technical strategy. You know when to address tech debt and when to improve infrastructure and processes (testing, code reviews, CI/CD).",
                      "marks": [],
                      "data": {}
                    }
                  ]
                }
              ]
            },
            {
              "nodeType": "list-item",
              "data": {},
              "content": [
                {
                  "nodeType": "paragraph",
                  "data": {},
                  "content": [
                    {
                      "nodeType": "text",
                      "value": "You’ll make the engineering team more effective. ",
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "data": {}
                    },
                    {
                      "nodeType": "text",
                      "value": "You’ll help us implement better processes, refine our interview process, and help define our engineering culture.",
                      "marks": [],
                      "data": {}
                    }
                  ]
                }
              ]
            },
            {
              "nodeType": "list-item",
              "data": {},
              "content": [
                {
                  "nodeType": "paragraph",
                  "data": {},
                  "content": [
                    {
                      "nodeType": "text",
                      "value": "You'll follow security best practices.",
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "data": {}
                    },
                    {
                      "nodeType": "text",
                      "value": " You will be responsible for safeguarding customer data, following secure coding guidelines, and adhering to Assembly’s security, confidentiality, and data protection policies as part of your work. You’ll help ensure that systems, code, and infrastructure are developed and maintained in alignment with our security standards.",
                      "marks": [],
                      "data": {}
                    }
                  ]
                }
              ]
            },
            {
              "nodeType": "list-item",
              "data": {},
              "content": [
                {
                  "nodeType": "paragraph",
                  "data": {},
                  "content": [
                    {
                      "nodeType": "text",
                      "value": "You'll help build the team. ",
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "data": {}
                    },
                    {
                      "nodeType": "text",
                      "value": "The first 10 members of an engineering team dictate the next 100. You'll help interview and recruit more talented engineers.",
                      "marks": [],
                      "data": {}
                    }
                  ]
                }
              ]
            },
            {
              "nodeType": "list-item",
              "data": {},
              "content": [
                {
                  "nodeType": "paragraph",
                  "data": {},
                  "content": [
                    {
                      "nodeType": "text",
                      "value": "You'll learn about startups",
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "data": {}
                    },
                    {
                      "nodeType": "text",
                      "value": ". Aside from your core work, you'll have the opportunity to get involved in other areas - marketing, growth, ops, etc.",
                      "marks": [],
                      "data": {}
                    }
                  ]
                }
              ]
            }
          ]
        },
        {
          "nodeType": "heading-2",
          "data": {},
          "content": [
            {
              "nodeType": "text",
              "value": "Who you are",
              "marks": [],
              "data": {}
            }
          ]
        },
        {
          "nodeType": "unordered-list",
          "data": {},
          "content": [
            {
              "nodeType": "list-item",
              "data": {},
              "content": [
                {
                  "nodeType": "paragraph",
                  "data": {},
                  "content": [
                    {
                      "nodeType": "text",
                      "value": "You're experienced.",
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "data": {}
                    },
                    {
                      "nodeType": "text",
                      "value": " You have 4+ years experience working on complex web applications built with modern tools and a proven track record as a lead developer. Familiarity with our tech stack is a bonus!",
                      "marks": [],
                      "data": {}
                    }
                  ]
                }
              ]
            },
            {
              "nodeType": "list-item",
              "data": {},
              "content": [
                {
                  "nodeType": "paragraph",
                  "data": {},
                  "content": [
                    {
                      "nodeType": "text",
                      "value": "You're passionate about crafting software.",
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "data": {}
                    },
                    {
                      "nodeType": "text",
                      "value": " Whether it's the thrilling moment when a scalable system design sparks excitement, or the deep satisfaction of engineering a seamless, robust frontend component, every line of code is a canvas for your creativity. You take pride in building systems that are as elegant as they are efficient, turning complex challenges into works of art that you love to share and showcase.",
                      "marks": [],
                      "data": {}
                    }
                  ]
                }
              ]
            },
            {
              "nodeType": "list-item",
              "data": {},
              "content": [
                {
                  "nodeType": "paragraph",
                  "data": {},
                  "content": [
                    {
                      "nodeType": "text",
                      "value": "You design thoughtful solutions.",
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "data": {}
                    },
                    {
                      "nodeType": "text",
                      "value": " You approach challenges by exploring multiple avenues, carefully weighing edge cases and dependencies to deliver the optimal user experience. You excel at articulating your ideas, ensuring that you remain focused on what truly matters: understanding customer needs.",
                      "marks": [],
                      "data": {}
                    }
                  ]
                }
              ]
            },
            {
              "nodeType": "list-item",
              "data": {},
              "content": [
                {
                  "nodeType": "paragraph",
                  "data": {},
                  "content": [
                    {
                      "nodeType": "text",
                      "value": "You love to collaborate, discuss and debate.",
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "data": {}
                    },
                    {
                      "nodeType": "text",
                      "value": " You engage in respectful, constructive debates—challenging ideas without being confrontational. You work collaboratively to weigh trade-offs and find balanced solutions, clearly explaining your reasoning when opinions differ and valuing the insights of your teammates.",
                      "marks": [],
                      "data": {}
                    }
                  ]
                }
              ]
            },
            {
              "nodeType": "list-item",
              "data": {},
              "content": [
                {
                  "nodeType": "paragraph",
                  "data": {},
                  "content": [
                    {
                      "nodeType": "text",
                      "value": "You're hardworking.",
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "data": {}
                    },
                    {
                      "nodeType": "text",
                      "value": " You understand that building a category-defining company requires people that work smart and that also work hard.",
                      "marks": [],
                      "data": {}
                    }
                  ]
                }
              ]
            },
            {
              "nodeType": "list-item",
              "data": {},
              "content": [
                {
                  "nodeType": "paragraph",
                  "data": {},
                  "content": [
                    {
                      "nodeType": "text",
                      "value": "You love working in person.",
                      "marks": [
                        {
                          "type": "bold"
                        }
                      ],
                      "data": {}
                    },
                    {
                      "nodeType": "text",
                      "value": " We're convinced that building a strong culture happens face-to-face, and we're looking for people who thrive in highly collaborative, in-person environments.",
                      "marks": [],
                      "data": {}
                    }
                  ]
                }
              ]
            }
          ]
        },
        {
          "nodeType": "heading-2",
          "data": {},
          "content": [
            {
              "nodeType": "text",
              "value": "Tech",
              "marks": [],
              "data": {}
            }
          ]
        },
        {
          "nodeType": "unordered-list",
          "data": {},
          "content": [
            {
              "nodeType": "list-item",
              "data": {},
              "content": [
                {
                  "nodeType": "paragraph",
                  "data": {},
                  "content": [
                    {
                      "nodeType": "text",
                      "value": "React, Typescript, Golang",
                      "marks": [],
                      "data": {}
                    }
                  ]
                }
              ]
            },
            {
              "nodeType": "list-item",
              "data": {},
              "content": [
                {
                  "nodeType": "paragraph",
                  "data": {},
                  "content": [
                    {
                      "nodeType": "text",
                      "value": "Libraries: Tailwind, MUI, Redux (rtk-query), AmplifyJS",
                      "marks": [],
                      "data": {}
                    }
                  ]
                }
              ]
            },
            {
              "nodeType": "list-item",
              "data": {},
              "content": [
                {
                  "nodeType": "paragraph",
                  "data": {},
                  "content": [
                    {
                      "nodeType": "text",
                      "value": "Infra (AWS): DynamoDB, Lambda, Cognito, Cloudwatch, Cloudformation, SQS",
                      "marks": [],
                      "data": {}
                    }
                  ]
                }
              ]
            }
          ]
        },
        {
          "nodeType": "paragraph",
          "data": {},
          "content": [
            {
              "nodeType": "text",
              "value": "",
              "marks": [],
              "data": {}
            }
          ]
        }
      ]
    },
    "team": [
      {
        "name": "Neil Raina",
        "profileLink": "https://www.linkedin.com/in/rnraina/",
        "image": {
          "url": "/images/cms/7qCB26EwQiIfi3DiZlGW8U-nr.webp",
          "alt": "Neil Raina"
        }
      },
      {
        "name": "Kevin Foley",
        "profileLink": "https://www.linkedin.com/in/kevin-foley-006337233/",
        "image": {
          "url": "/images/cms/6v2Pbh7pK2qCULeEO7D3uq-kf.webp",
          "alt": "Kevin"
        }
      },
      {
        "name": "Sal Becker",
        "profileLink": "https://www.linkedin.com/in/salbecker/",
        "image": {
          "url": "/images/cms/1GvOERkr84S7vTi0Pjccih-t6fa6ee67-u0745qm67pd-ab46234e1459-512.webp",
          "alt": "Sal Becker Profile"
        }
      }
    ]
  }
] as unknown as JobListing[];
