// 12 frozen pages: the team profiles, as Contentful held them the day
// they were taken out of it. This file IS the source — there is no CMS read
// behind it any more, so a copy change is an edit here and a deploy.
//
// Generated by scripts/freeze-cms.mts. Regenerating overwrites hand edits, so
// once you start editing the copy here, stop regenerating: the CMS entries are
// no longer maintained. Imagery lives in public/images/cms, downloaded with it.
import type { TeamProfile } from "./team-profiles";

export const FROZEN_TEAM: TeamProfile[] = [
  {
    "name": "Adam Seitzman",
    "about": "Head of Sales and Partnerships",
    "profileLink": "https://www.linkedin.com/in/adamseitzman/",
    "photo": {
      "url": "/images/cms/6Pqyb4LGLy6gIqnaQMvHm2-ada.webp",
      "alt": "Adam Seitzman",
      "width": 800,
      "height": 800
    }
  },
  {
    "name": "Allene Norton",
    "about": "Head of Customer Support and Developer Relations",
    "profileLink": "https://www.linkedin.com/in/allene-norton/",
    "photo": {
      "url": "/images/cms/3zRartke5P7XAH1IAvj25s-an.webp",
      "alt": "Allene Norton",
      "width": 459,
      "height": 459
    }
  },
  {
    "name": "Marlon Misra",
    "about": "Founder + CEO",
    "profileLink": "https://www.linkedin.com/in/marlonmisra/",
    "photo": {
      "url": "/images/cms/467AAyP0ueqdADoYTy63hR-pp.webp",
      "alt": "Marlon Misra",
      "width": 160,
      "height": 160
    }
  },
  {
    "name": "Potluck Mittal",
    "about": "Product Manager",
    "profileLink": "https://www.linkedin.com/in/potluck/",
    "photo": {
      "url": "/images/cms/5FWkWuh6H7IFZSOEKxhGW8-pl.webp",
      "alt": "Potluck Mittal",
      "width": 800,
      "height": 800
    }
  },
  {
    "name": "Brittany Nickell",
    "profileLink": "https://www.linkedin.com/in/brittanyleighnickell/",
    "photo": {
      "url": "/images/cms/6Wtzv2ER7HK1wujQne8v1c-britt.webp",
      "alt": "Brittany Nickell",
      "width": 512,
      "height": 512
    }
  },
  {
    "name": "Dovid Baum",
    "profileLink": "https://www.linkedin.com/in/dovidbaum/",
    "photo": {
      "url": "/images/cms/1XMHKVfSXDeiCrHjEDKj4-screenshot_2024-08-07_at_2.09.25_pm.webp",
      "alt": "Dovid Baum",
      "width": 1052,
      "height": 938
    }
  },
  {
    "name": "Ezeugo Anukem",
    "profileLink": "https://www.linkedin.com/in/ezeugo/",
    "photo": {
      "url": "/images/cms/7EnvY6PyL0MIixvs6vgaWE-ez.webp",
      "alt": "Ezeugo Anukem",
      "width": 460,
      "height": 460
    }
  },
  {
    "name": "Kevin Foley",
    "profileLink": "https://www.linkedin.com/in/kevin-foley-006337233/",
    "photo": {
      "url": "/images/cms/6v2Pbh7pK2qCULeEO7D3uq-kf.webp",
      "alt": "Kevin Foley",
      "width": 800,
      "height": 800
    }
  },
  {
    "name": "Neil Raina",
    "profileLink": "https://www.linkedin.com/in/rnraina/",
    "photo": {
      "url": "/images/cms/7qCB26EwQiIfi3DiZlGW8U-nr.webp",
      "alt": "Neil Raina",
      "width": 453,
      "height": 500
    }
  },
  {
    "name": "Sal Becker",
    "profileLink": "https://www.linkedin.com/in/salbecker/",
    "photo": {
      "url": "/images/cms/1GvOERkr84S7vTi0Pjccih-t6fa6ee67-u0745qm67pd-ab46234e1459-512.webp",
      "alt": "Sal Becker",
      "width": 512,
      "height": 512
    }
  },
  {
    "name": "Sean Walsh",
    "profileLink": "https://www.linkedin.com/in/seanwalshnyc/",
    "photo": {
      "url": "/images/cms/mn6yQCTnVVBh9YVmqbWf5-screenshot_2024-08-07_at_2.11.11_pm.webp",
      "alt": "Sean Walsh",
      "width": 1096,
      "height": 1080
    }
  },
  {
    "name": "Veronique Cadet",
    "profileLink": "https://www.linkedin.com/in/v%C3%A9roniquecadet/",
    "photo": {
      "url": "/images/cms/3aoCGbZrlalK0pR7WTr8Yo-ver.webp",
      "alt": "Veronique Cadet",
      "width": 192,
      "height": 192
    }
  }
];
