import Link from "next/link";

// ─────────────────────────────────────────────────────────────────────────
// THE WHOLE STACK — itemizes the proof behind the production-gap claim:
// everything a firm would otherwise build or buy after a code generator
// hands them an app. Section 3 asserts the gap; each row here lands as
// evidence. Copy from the landing narrative doc.
// ─────────────────────────────────────────────────────────────────────────

const ROWS: { title: string; body: string; href?: string; linkLabel?: string }[] = [
  {
    title: "Client authentication, built in",
    body: "Secure magic links and Google Auth for your clients.",
  },
  {
    title: "Permissions your team controls",
    body: "Roles and client scoping are platform infrastructure — maintained by humans, not generated by AI.",
  },
  {
    title: "Security the AI can't get wrong",
    body: "A structural boundary separates your team from your clients — no prompt can cross it.",
    href: "/security",
    linkLabel: "View security",
  },
  {
    title: "Your CRM, already connected",
    body: "Every app knows your contacts and companies from day one — no data silos, nothing to rebuild.",
  },
  {
    title: "Your brand and domain, automatic",
    body: "Every app ships with your logo, colors, and custom domain.",
  },
  {
    title: "Notifications, both audiences",
    body: "In-product and email, for your team and your clients.",
  },
  {
    title: "Backend and storage, handled",
    body: "Hosting, database, and deployment with nothing to configure.",
  },
];

export function WholeStack() {
  return (
    <section id="whole-stack" className="py-20 md:py-28">
      <div className="mx-auto max-w-[1600px] px-6 md:px-10">
        <h2 className="type-h2 max-w-xl text-foreground">
          Everything after the prompt, already built.
        </h2>
        <p className="type-lead mt-5 max-w-xl text-muted-foreground">
          Ship a real app without wiring up auth, configuring a database, or
          figuring out how clients log in. Assembly is the foundation your
          apps are born into — not infrastructure you assemble around them.
        </p>

        {/* Spec-table rows — title on the left, evidence on the right, echoing
            the hairline list language of How it works. */}
        <div className="mt-12 border-b border-border">
          {ROWS.map((row) => (
            <div
              key={row.title}
              className="grid gap-2 border-t border-border py-5 md:grid-cols-[minmax(0,340px)_minmax(0,1fr)] md:gap-12"
            >
              <h3 className="text-[17px] text-foreground">{row.title}</h3>
              <p className="text-[15px] leading-relaxed text-muted-foreground">
                {row.body}
                {row.href && (
                  <>
                    {" "}
                    <Link
                      href={row.href}
                      className="whitespace-nowrap text-foreground underline decoration-border underline-offset-4 transition-colors hover:decoration-foreground"
                    >
                      {row.linkLabel}
                    </Link>
                  </>
                )}
              </p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
